config/routes.rb
Campusbooks::Application.routes.draw do

  post "sessions/set", to: 'sessions#set'

  get "home/index"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'  
  resources :queries do
   resources :responses
  end
  
  resources :users

  resources :books do    
    member do
      get 'buy' 
      get 'sold'     
    end    
    collection do
      get 'mybooks'      
    end
  end  

  root :to => 'home#index'

end

app/models/book.rb
class Book
  include Mongoid::Document
  field :title, type: String
  field :author, type: String
  field :sold, type: Boolean
  field :isbn, type: String
  field :image_url, type: String
  field :semester, type: String
  field :price, type: String
  field :pages, type: String
  field :created_at, type: DateTime, :default => Time.now

  validates_presence_of :title,:author,:semester,:price
  validates_numericality_of :price
  belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.where(:sold => 'false').desc(:created_at).paginate(:page => params[:page], :per_page => 9)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create    
    user = User.find_by(_id: session[:user_id])
    @book = user.books.new(params[:book])
    @book.sold = false
    @book.pages = if params[:book][:pages].nil?
      '-'
    else
      params[:book][:pages]
    end

    #OPENLIB

    if !params[:book][:isbn].blank?
      details = Openlibrary::Data
      book_view = details.find_by_isbn(params[:book][:isbn])
      @book.image_url = if !book_view.nil?
        book_view.cover['large']
      else
        'http://placehold.it/180x240&text=No+Image,+Yo!'
      end
    else
      @book.image_url =  'http://placehold.it/180x240&text=No+Image,+Yo!'
    end

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    if !params[:book][:isbn].blank?
      details = Openlibrary::Data
      book_view = details.find_by_isbn(params[:book][:isbn])
      @book.image_url = if !book_view.nil?
        book_view.cover['large']
      else
        'http://placehold.it/180x240&text=No+Image,+Yo!'
      end
    else
      @book.image_url =  'http://placehold.it/180x240&text=No+Image,+Yo!'
    end

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  def buy    
    session[:buying_book_id] = params[:id]
    @book = Book.find_by(_id: params[:id])
    @user = User.find_by(_id: @book.user_id)
  end

  def mybooks
    user = User.find_by(_id: session[:user_id])    
    @books = user.books.where(user_id: user._id).paginate(:page => params[:page], :per_page => 12)
  end

  def sold
    book = Book.find_by(_id: params[:id])
    book.update_attribute(:sold, true)    
    redirect_to :back
  end

  def add_image(isbn)
    
  end
end

app/helpers/books_helper.rb
module BooksHelper
	def get_username_from_book_id(book_id)
		book = Book.find_by(_id: book_id)
		user = User.find_by(_id: book.user_id)
		username = user.name		
	end
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <div>
    <% if @book.errors.any? %>
      <div class="alert alert-danger">
        
        <h2>Danger!,Danger!</h2>
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <table class="table table-bordered table-striped">
      <tr>
        <td>
          <strong>
            <%= f.label :title %>
          </strong>
        </td>
        <td>
          <%= f.text_field :title, :placeholder => 'Enter a Title' %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>
            <%= f.label :author %>
          </strong>
        </td>
        <td>
          <%= f.text_field :author, :placeholder => 'Enter the Author\'s Name' %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>
            <%= f.label :semester %>
          </strong>
        </td>
        <td>
          <%= f.select :semester, (1..8) %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>
            <%= f.label :price %>
          </strong>
        </td>
        <td>
          <div class="input-prepend input-append">
            <span class="add-on">
              &#8377;
            </span>
            <%= f.text_field :price, :class => 'input-mini' %>
            <span class="add-on">
              .00
            </span>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <strong>
            <%= f.label :pages %>
          </strong>
        </td>
        <td>
          <%= f.text_field :pages, :placeholder => 'Number of Pages' %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>
            <%= f.label :isbn, "ISBN" %> <p class="muted">* Optional</p>
          </strong>
        </td>
        <td>
          <%= f.text_field :isbn, :placeholder => 'ISBN' %>
        </td>
      </tr>
    </table>
    <div class="form-actions clearfix">
      <%= button_tag(type: 'submit', class: "btn btn-success green ") do %>
       <i class="icon-ok icon-white"></i> <%= label %>
      <% end %>
      <%= button_tag(type: 'reset', class: "btn white ") do %>
       <i class="icon-refresh icon-white" style="padding:2px"></i> Reset
      <% end %>
    </div>
  </div>
<% end %>

app/views/books/buy.html.erb
<div class="modal hide fade" id="buymodal">
	<div class="modal-header">
		<div class="pull-right"><a href="/books" data-dismiss="modal" class="close">&times;</a></div>
		<h3>
			Buy <%= @book.title %>
		</h3>
	</div>
	<div class="modal-body">		
		<p>
			Would you like to buy <%= @book.title %> from <%= @user.first_name %> ?
		</p>
	</div>
	<div class="modal-footer">		
		<%= link_to 'Yes', new_query_path, :class => 'btn btn-primary' %>
		<%= link_to 'No', books_path, :class => 'btn' %>
	</div>
</div>
<div class="container">
	<div class="row well">
		<div class="page-header">
			<h1>
				<%= @book.title %>
				<div class="status pull-right">
					<% if @book.sold %>
					  <span class="badge badge-important">
					  	SOLD
					  </span>
					<% else %>
					  <span class="badge badge-success">
					  	FOR SALE
					  </span>
					<% end %>
				</div>
			</h1>
		</div>
		<div class="content">
			<div class="pull-left">
				<div class="thumbnail">
					<span class="thumbnail"><%= image_tag(@book.image_url,:alt => 'No Image', :style => "height: 240px; max-width: 180px;") %></span>
				</div>
			</div>
			<div class="span9 pull-right details">
				<table class="table table-bordered table-striped">
					<tr>
						<td>
							<strong>
								Title
							</strong>
						</td>
						<td>
							<%= @book.title %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								Author
							</strong>
						</td>
						<td>
							<%= @book.author %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								Semester
							</strong>
						</td>
						<td>
							<%= @book.semester %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								Price
							</strong>
						</td>
						<td>
							&#8377; <%= @book.price %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								Pages
							</strong>
						</td>
						<td>
							<% if @book.pages.to_i != 0 %>
							  <%= pluralize(@book.pages, 'Page') %>
							<% else %>
							  -
							<% end %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								ISBN
							</strong>
						</td>
						<td>
							<% if @book.isbn.to_i != 0 %>
							  <%= @book.isbn %>
							<% else %>
							  -
							<% end %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								Posted By
							</strong>
						</td>
						<td>
							<%= get_username_from_id(@book.user_id) %>
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="actions">
					<hr />			
				<div class="pull-left">
						<%= link_to '<i class="icon-arrow-left" style="padding:4px"></i> Back'.html_safe, :back, :class => 'btn small white' %>
				</div>
				<div class="pull-right" style="padding:5px">
						<% if can? :edit, @book %>
						  <%= link_to '<i class="icon-edit" style="padding:4px"></i> Edit'.html_safe, edit_book_path(@book), :class => 'btn btn-warning yellow small' %>
						  <%= link_to '<i class="icon-trash" style="padding:4px"></i> Delete'.html_safe, book_path(@book), :method => :delete, :class => 'btn btn-danger red small', :confirm => 'Are you sure you want to delete this book?' %>
						  <% if !@book.sold %>
						    <%= link_to '<i class="icon-thumbs-up" style="padding:4px"></i> Sold'.html_safe, sold_book_path(@book), :class => 'btn btn-info orange small' %>
						  <% end %>
						<% else %>
						    <%= link_to '<i class="icon-shopping-cart" style="padding:4px"></i> Buy'.html_safe, '#', :'data-toggle' => 'modal', :'data-target' => 'buymodal', :class => 'btn btn-success' %>
						<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/books/edit.html.erb
<div class="container">
	<div class="row well">
		<div class="page-header">
			<h1>
				Edit Book
				<small>
					<%= @book.title %>
				</small>
			</h1>
		</div>
		<div class="content">
			<%= render 'form', :label => "Update Book" %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
        <br>
        <br><br>
        <div class="page-header">
          <h1>
            Books
            <small>
              For Sale
            </small>
          </h1>
        </div>
        <% if !@books.blank? %>
          <% @books.each do |book| %>
            <div class="well">
              <h4>
                <%= link_to book.title, book %>
              </h4>
              <hr />
              <p>
                Author : <%= book.author %>
              </p>
              <br />
              <p>
                Price : &#8377; <%= book.price %>
              </p>
              <%= link_to '<i class="icon-shopping-cart icon-white"></i> Buy this book'.html_safe, buy_book_path(book), :class => 'button small green pull-right' %>
            </div>
          <% end %>
        <% else %>
          <div class="well alert alert-error">
            <p>
              <i class="icon-exclamation-sign" style="color:maroon;font-size:25px;"></i>&nbsp;&nbsp;&nbsp;There are no books for sale right now.
            </p>
          </div>
        <% end %>
        <div class="pagination-centered">
          <%= will_paginate @books, :renderer => BootstrapPagination::Rails %>
        </div>
  </div>
</div>

app/views/books/mybooks.html.erb
<div class="container">
  <div class="row span12">
        <div class="page-header">
          <h1>
            My Books
            <small>
              Books I've posted
            </small>
          </h1>
        </div>
        <% if !@books.blank? %>
        <div class="">
          <% @books.each do |book| %>
            <div class="well span3">
              <h4>
                <%= link_to truncate(book.title,:length => 21), book, :rel => 'tooltip', :'data-original-title' => book.title, :'data-trigger' => 'hover',  :id => 'book_title' %>
              </h4>
              <hr />
              <div>
                <p>
                  Author : <%= book.author %>
                </p>
                <br />
                <p>
                  Price : &#8377; <%= book.price %>
                </p>
              </div>
              <hr>
              <p class="pull-left">
              	Status : 
              </p>
              <p class="pull-right">
              	<% if book.sold %>
              	  <span class="badge badge-important">SOLD</span>
              	<% else %>
              	  <span class="badge badge-success">FOR SALE</span>
              	<% end %>
              </p>
            </div>
          <% end %>
        <% else %>
          <div >
            <p class="alert alert-error">
              <i class="icon-exclamation-sign" style="color:maroon;font-size:20px;"></i>&nbsp;&nbsp;&nbsp;You haven't posted any Books yet.
            </p>
          </div>
        <% end %>
        </div>
        <div class="pagination-centered">
          <%= will_paginate @books, :renderer => BootstrapPagination::Rails %>
        </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
	<div class="row well">
		<div class="page-header">
			<h1>
				Add a Book
			</h1>
		</div>
		<div class="content">
			<%= render 'form', :label => "Create" %>
		</div>
	</div>
</div>

app/views/books/sell.html.erb
<h2>Sell</h2>
<%= link_to 'Add Book', new_book_path %>

<h3>
	My Books
</h3>
<% @mybooks.each do |mybook| %>
<div>
	<h6>
		<%= link_to mybook.title, book_path(mybook) %>
	</h6>
	<br />
</div>
<% end %>

<hr />

app/views/books/show.html.erb
<div class="container">
	<div class="row well">
		<div class="page-header">
			<h1>
				<%= @book.title %>
				<div class="status pull-right">
					<% if @book.sold %>
					  <span class="badge badge-important">
					  	SOLD
					  </span>
					<% else %>
					  <span class="badge badge-success">
					  	FOR SALE
					  </span>
					<% end %>
				</div>
			</h1>
		</div>
		<div class="content">
			<div class="pull-left">
				<div class="thumbnail">
					<span class="thumbnail"><%= image_tag(@book.image_url,:alt => 'No Image', :style => "height: 240px; max-width: 180px;") %></span>
				</div>
			</div>
			<div class="span9 pull-right details">
				<table class="table table-bordered table-striped">
					<tr>
						<td>
							<strong>
								Title
							</strong>
						</td>
						<td>
							<%= @book.title %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								Author
							</strong>
						</td>
						<td>
							<%= @book.author %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								Semester
							</strong>
						</td>
						<td>
							<%= @book.semester %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								Price
							</strong>
						</td>
						<td>
							&#8377; <%= @book.price %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								Pages
							</strong>
						</td>
						<td>
							<% if @book.pages.to_i != 0 %>
							  <%= pluralize(@book.pages, 'Page') %>
							<% else %>
							  -
							<% end %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								ISBN
							</strong>
						</td>
						<td>
							<% if @book.isbn.to_i != 0 %>
							  <%= @book.isbn %>
							<% else %>
							  -
							<% end %>
						</td>
					</tr>
					<tr>
						<td>
							<strong>
								Posted By
							</strong>
						</td>
						<td>
							<%= get_username_from_id(@book.user_id) %>
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="actions">
					<hr />			
				<div class="pull-left">
						<%= link_to '<i class="icon-arrow-left" style="padding:4px"></i> Back'.html_safe, :back, :class => 'btn small white' %>
				</div>
				<div class="pull-right" style="padding:5px">
						<% if can? :edit, @book %>
						  <%= link_to '<i class="icon-edit" style="padding:4px"></i> Edit'.html_safe, edit_book_path(@book), :class => 'btn btn-warning yellow small' %>
						  <%= link_to '<i class="icon-trash" style="padding:4px"></i> Delete'.html_safe, book_path(@book), :method => :delete, :class => 'btn btn-danger red small', :confirm => 'Are you sure you want to delete this book?' %>
						  <% if !@book.sold %>
						    <%= link_to '<i class="icon-thumbs-up" style="padding:4px"></i> Sold'.html_safe, sold_book_path(@book), :class => 'btn btn-info orange small' %>
						  <% end %>
						<% else %>
						    <%= link_to '<i class="icon-shopping-cart" style="padding:4px"></i> Buy'.html_safe, buy_book_path(@book), :class => 'btn btn-success green small' %>
						<% end %>
				</div>
			</div>
		</div>
	</div>
</div>