config/routes.rb
Campusbooks::Application.routes.draw do

  post "sessions/set", to: 'sessions#set'

  get "home/index"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'  
  resources :queries do
   resources :responses
  end
  
  resources :users

  resources :books do    
    member do
      get 'buy' 
      get 'sold'     
    end    
    collection do
      get 'mybooks'      
    end
  end  

  root :to => 'home#index'

end

app/models/query.rb
class Query
  include Mongoid::Document
  field :book_id, type: String
  field :sender_id, type: String
  field :receiver_id, type: String
  field :body, type: String
  field :seen, type: Boolean
  field :created_at, type: DateTime, :default => Time.now

  has_many :responses, dependent: :destroy

  def self.unread
  	where(:seen => false)
  end

  def self.read
    where(:seen => true)
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController

	def index
	  @user = User.find_by(_id: session[:user_id])
	  @messages = Query.where(receiver_id: @user._id).desc(:created_at).paginate(:page => params[:page], :per_page => 4) || Response.where(receiver_id: @user._id)
	  responses_sent = Response.where(sender_id: @user_id).desc(:created_at)
	  queries_sent = Query.where(sender_id: @user_id).desc(:created_at)
	  @sentmessages = responses_sent.zip(queries_sent).flatten.compact
	  # @sentmessages = Query.where(sender_id: @user._id).desc(:created_at).paginate(:p age => params[:page], :per_page => 4)
	end

	def new		
		@query = Query.new
		@book = Book.find_by(_id: session[:buying_book_id])
		@user = User.find_by(_id: @book.user_id)
	end

	def create	
		@query = Query.new(params[:query])
		book_id = session[:buying_book_id]	
		sender = User.find_by(_id: session[:user_id])
		book = Book.find_by(_id: book_id)	
		
		@query.book_id = book._id
		@query.receiver_id = book.user_id
		@query.sender_id = sender._id
		@query.body = params[:query][:body]
		@query.seen = false

		if @query.save!
		  redirect_to query_path(@query), :notice => "Your message was sent successfully!"
		else
		  render action: "new", :notice => @query.errors, status: :unprocessable_entity
		end
		session[:buying_book_id] = nil
	end

	def show
		# @user = User.find_by(_id: session[:user_id])
		# @query = Query.find_by(_id: params[:id])	
		# @book = Book.find_by(_id: @query.book_id)
		# @query.update_attribute(:seen,true)
		# @query.responses.last.update_attribute(:seen,true) if @query.responses.count > 0
		# @response = @query.responses.new
		@query = Query.find_by(_id: params[:id])
		@user = User.find_by(_id: @query.sender_id)
		if session[:user_id] === @query.receiver_id
		  @query.update_attribute(:seen,true)
		  @query.responses.update_all(seen: true)
		end	
		@book  = Book.find_by(_id: @query.book_id)
		# @response = @query.responses.new
	end

end

app/helpers/queries_helper.rb
module QueriesHelper
	def has_unread_responses?(message)
	  unread = if message.responses.where(seen: false).count > 0
	  	true
	  elsif message.responses.where(seen: false).count === 0
	  	false
	  else
	  	false
	  end
	  return unread
	end
end

app/views/queries/_form.html.erb
<%= form_for(@query) do |f| %>
    <div>
		<%= f.text_area :body, :cols => 80, :rows => 5, :class => 'span10', :placeholder => 'Enter your query here..' %>  	
	</div>
  	<div class="form-actions clearfix">
  	  <%= button_tag(type: 'submit', class: "btn btn-success green ") do %>
  	   <i class="icon-ok icon-white"></i> Send
  	  <% end %>
  	  <%= button_tag(type: 'reset', class: "btn white ") do %>
  	   <i class="icon-refresh icon-white" style="padding:2px"></i> Reset
  	  <% end %>
  	</div>
<% end %>

app/views/queries/index.html.erb
<div class="container">
	<div class="well">
		<div class="page-header">
			<h1>
				Messages
				<small>
					Unread : <%= notifications %>
				</small>
			</h1>
		</div>
		<div id="inbox">
			<h4>Inbox</h4>
			<% if !@messages.blank? %>
			  <% @messages.each do |message| %>
			    <div class="well messages">
			    	<div class="info">
			    		<div class="pull-left">
			    			<%= image_tag get_imgurl_from_id(message.sender_id), :class => 'thumbnail img-rounded' %>
			    		</div>
			    		<div class="name span4 pull-left">
			    			<p>
			    				<%= link_to get_username_from_id(message.sender_id), user_path(message.sender_id) %>
			    			</p>
			    		</div>
			    	</div>
			    	<span class="divider"></span>
			    	<div class="message">
			    		<% if message.seen && !has_unread_responses?(message) %>
			    		  <%= link_to message.body, query_path(message) %>
			    		<% else %>
			    		  <strong>
			    		  	<%= link_to message.body, query_path(message) %>
			    		  </strong>
			    		<% end %>
			    	</div>
			    </div>
			  <% end %>
			<% else %>
			  <p class="alert alert-danger">
			    No Messages to display.
			  </p>
			<% end %>
		</div>
		<div id="sent">
			<h4>Sent Messages</h4>
			<%= @unread_responses_count %>
			<% if !@sentmessages.blank? %>
			  <% @sentmessages.each do |sent_message| %>
			    <div class="well">
			    	<%= link_to sent_message.body, query_path(sent_message) %>
			    </div>
			  <% end %>
			<% else %>
			  <p class="alert alert-danger">
			  	No Messages to display.
			  </p>
			<% end %>
		</div>
	</div>
</div>

app/views/queries/new.html.erb
<div class="container">
	<div class="row well">
		<div class="page-header">
			<h1>
				Buy <%= link_to @book.title, book_path(@book) %>
				<br />
				<small>
					Conversation with <%= @user.name %>
				</small>
			</h1>
		</div>
		<%= render 'form' %>
	</div>
</div>

app/views/queries/show.html.erb
<div class="container">
  <div class="row well">
    <div class="page-header">
      <h1>
        Conversation with <%= get_username_from_id(@query.receiver_id) %>
        <br />
        <small>
          Book : <%= link_to @book.title, book_path(@book) %>
          <div class="pull-right">
             <%= link_to 'Back', queries_path, :class => 'act-info' %>
          </div>
        </small>
      </h1>
    </div>
    <div class="query well">
      <div>
        <%= image_tag @user.picture_url, :class => 'thumbnail', :style => 'vertical-align: middle' %>
      </div>
      <h5>
        <%= @user.name %>
      </h5>
      <p>
        <%= @query.body %>
      </p>
    </div>
    <hr>
    Res
    <div class="responses">
      <% if !@query.responses.blank? %>
        <% @query.responses.each do |response| %>
         <% if response.seen %>
           <div class="well">
             <div>
                 <%= image_tag get_imgurl_from_id(response.sender_id), :class => 'thumbnail' %>
             </div>
             <div class="title">
               <strong>
                 <%= get_username_from_id(response.sender_id) %>
               </strong>
             </div>
             <div class="content">
               <p>
                 <%= response.body %>
               </p>
             </div>
           </div>
          <% else %>
            <div class="well">
              <div>
                  <%= image_tag get_imgurl_from_id(response.sender_id), :class => 'thumbnail' %>
              </div>
              <div class="title">
                <strong>
                  <%= get_username_from_id(response.sender_id) %>
                </strong>
              </div>
              <div class="content">
                <p>
                  <strong>
                    <%= response.body %>
                  </strong>
                </p>
              </div>
            </div>
         <% end %>
        <% end %>
      <% end %>
      <hr />
      <% @response = @query.responses.new %>
      <%= render 'responses/form', :response => @response, :query => @query %>
    </div>
  </div>
</div>