config/routes.rb
Campusbooks::Application.routes.draw do

  post "sessions/set", to: 'sessions#set'

  get "home/index"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'  
  resources :queries do
   resources :responses
  end
  
  resources :users

  resources :books do    
    member do
      get 'buy' 
      get 'sold'     
    end    
    collection do
      get 'mybooks'      
    end
  end  

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Campus Books | SRM University</title>
  <%= google_webfonts_link_tag 'Amaranth','Open Sans' %>
  <%= stylesheet_link_tag "application", :media => "all" %>  
  <%= csrf_meta_tags %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-37200107-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  <%= javascript_include_tag "application" %>
</head>
<body style="font-family: 'Open Sans', sans-serif;">
	<% if current_user %>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">	  	
	    <a class="brand" href="/" style="margin-left:10px;"><i class="iconic-book-alt2" style="padding:4px"></i>&nbsp;Campus Books</a>
	    	<ul class="nav pull-right">	    		  		
	    		<li class="dropdown" style="padding-bottom:5px;">	    				    		
	    			<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-target="#" style="padding-bottom: 0px;">
	    				<div>
	    					<img src="<%= current_user.picture_url %>" height="30" width="30" class="img-rounded" alt="<%= current_user.name %>">
	    					<%= current_user.name %>
	    					<i class="icon-caret-down" style="padding:2px"></i>
	    				</div>
	    			</a>
	    			<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">		        
	    				<li>
	    					<%= link_to '<i class="iconic-book"></i> Sell a Book'.html_safe, new_book_path %>
	    				</li>
	    				<li>
	    					<%= link_to '<i class="iconic-book-alt2"></i> My Books'.html_safe, mybooks_books_path %>
	    				</li>
	    				<li>
	    				
	    					<a href="<%= queries_path %>">
	    						<i class="iconic-comment-alt2-stroke"></i> Messages
	    						  <% if notifications != 0 %>
		    						  <span class="badge badge-success">
		    						  	<%= notifications %>
	    							  </span>
	    						  <% end %>
	    					</a>
	    				</li>
	    				<li class="divider"></li>
	    				<li>
	    					<%= link_to '<i class="iconic-curved-arrow"></i> Sign Out'.html_safe, signout_path %>
	    				</li>
	    			</ul>
	    		</li>	    		
	    	</ul>	   
	  </div>
	</div>		
	<% end %>
<%= yield %>
</body>
<%= yield :scripts %>
</html>